### ISSUE TITLE
npm

### ISSUE THREAD

**Issue by phated** [jamen/cah-cards#1]
Hey @jamen - do you want the npm package? https://www.npmjs.com/package/cah-cards - I haven't worked on it in ages because I left my previous company that was using it.

**Comment by jamen** [comment]
@phated I would appreciate it, thanks. :smile:

`npm owner add jamen cah-cards`

I didn't even know it was used at the time, otherwise I would have used `@jamen/cah-cards`.  :sweat_smile:

**Comment by phated** [comment]
Done
